#!/usr/bin/env python3
"""
notebooklm_deepdive.py — gem-notebooklm Orchestrator
══════════════════════════════════════════════════════
ONE-WAY PIPELINE: lawmodel1 → NotebookLM (outbound only)

  1. Query evidence_hub.db (READ-ONLY — never writes)
  2. Generate a timestamped case-context brief (markdown)
  3. Tell you exactly where to upload it in NotebookLM
  4. You generate the Audio Overview manually in NotebookLM
  5. You download the MP3 and store it OUTSIDE this workspace

Audio overviews are AI-generated analysis. They never re-enter
this workspace or evidence_hub.db. One-way, no return path.

Usage:
  python scripts/notebooklm_deepdive.py                        # All templates
  python scripts/notebooklm_deepdive.py --template new-evidence-spotlight
  python scripts/notebooklm_deepdive.py --days 7               # Last 7 days
  python scripts/notebooklm_deepdive.py --dry-run              # Preview brief only
  python scripts/notebooklm_deepdive.py --list-templates       # List options
  python scripts/notebooklm_deepdive.py --output-dir ~/Desktop/RC-NLM-Briefs
"""

import sys
import json
import argparse
import sqlite3
from pathlib import Path
from datetime import datetime, timedelta, timezone

# ──────────────── PATHS ────────────────
BASE_DIR       = Path("/Volumes/batdrivetb5/AI_TRAINING/lawmodel1")
EVIDENCE_HUB   = BASE_DIR / "data" / "evidence_hub.db"
TEMPLATES_FILE = BASE_DIR / "prompts" / "notebooklm_templates.json"
# Default output dir — override with --output-dir to keep briefs outside the workspace
DEFAULT_BRIEFS_DIR = Path.home() / "Documents" / "RC-NLM-Briefs"

# ──────────────── LOGGING ────────────────
def log(msg, level="INFO"):
    icon = {"INFO": "[*]", "OK": "[✓]", "WARN": "[!]", "ERR": "[✗]"}.get(level, "[*]")
    print(f"{icon} {msg}")


# ──────────────── EVIDENTIARY FIREWALL ────────────────
# This script is READ-ONLY with respect to evidence_hub.db.
# Briefs are outbound-only. Audio downloads happen outside this workspace.
NOT_EVIDENCE_BANNER = """\
⚠  NOT EVIDENCE — AI-GENERATED ANALYSIS ONLY
   This brief is derivative work. It exists solely to seed NotebookLM's
   Audio Overview engine. NEVER ingest it back into evidence_hub.db.
   Download audio files OUTSIDE this workspace.
"""

NOT_EVIDENCE_MD_HEADER = """\
> **⚠ NOT EVIDENCE — AI ANALYSIS BRIEF**
> Generated by gem-notebooklm. This is derivative work — an AI-synthesized
> summary of case evidence for internal analysis only. It must never be:
> ingested into evidence_hub.db · cited in legal filings · treated as fact
> without independent verification against original source records.
"""


# ──────────────── EVIDENCE QUERY (READ-ONLY) ────────────────
def get_new_evidence(days: int = 30) -> list[dict]:
    """Pull recent evidence from evidence_hub.db. READ-ONLY."""
    if not EVIDENCE_HUB.exists():
        log(f"evidence_hub.db not found at {EVIDENCE_HUB}", "WARN")
        return []

    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    try:
        with sqlite3.connect(f"file:{EVIDENCE_HUB}?mode=ro", uri=True) as conn:
            conn.row_factory = sqlite3.Row
            cur = conn.execute(
                """
                SELECT id, title, summary, body_snippet, source_type, tags, start_timestamp
                FROM evidence
                WHERE created_at >= ?
                ORDER BY start_timestamp DESC
                LIMIT 100
                """,
                (cutoff,)
            )
            rows = [dict(r) for r in cur.fetchall()]
            log(f"Found {len(rows)} evidence records (last {days} days)", "OK")
            return rows
    except Exception as ex:
        log(f"Error querying evidence_hub.db: {ex}", "WARN")
        return []


def get_evidence_stats() -> dict:
    """Overall evidence counts. READ-ONLY."""
    if not EVIDENCE_HUB.exists():
        return {}
    try:
        with sqlite3.connect(f"file:{EVIDENCE_HUB}?mode=ro", uri=True) as conn:
            rows = conn.execute(
                "SELECT source_type, COUNT(*) FROM evidence GROUP BY source_type ORDER BY 2 DESC"
            ).fetchall()
            by_type = {r[0]: r[1] for r in rows}
            total = sum(by_type.values())
            last = conn.execute("SELECT MAX(created_at) FROM evidence").fetchone()[0]
            return {"total": total, "by_type": by_type, "last_ingested": last}
    except Exception:
        return {}


# ──────────────── BRIEF GENERATOR ────────────────
def generate_brief(evidence: list[dict], template: dict, preamble: str) -> str:
    """Build the outbound markdown brief to upload to NotebookLM."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    stats = get_evidence_stats()

    lines = [
        f"# RC-2026 NotebookLM Brief — {template['name']}",
        f"*{now} | gem-notebooklm | ONE-WAY OUTBOUND*",
        "",
        NOT_EVIDENCE_MD_HEADER,
        "",
        "---",
        "",
        preamble,
        "",
        "## Evidence Snapshot",
        f"- **Total records:** {stats.get('total', 'n/a')}",
        f"- **Last ingested:** {stats.get('last_ingested', 'unknown')}",
        "",
    ]

    if stats.get("by_type"):
        lines.append("### By Type")
        for src, cnt in stats["by_type"].items():
            lines.append(f"- {src}: {cnt}")
        lines.append("")

    if evidence:
        lines += [
            f"## Recent Evidence ({len(evidence)} items, last session)",
            "",
        ]
        for i, ev in enumerate(evidence[:50], 1):
            tags = ev.get("tags") or ""
            date = (ev.get("start_timestamp") or "")[:10] or "unknown"
            body = ev.get("summary") or ev.get("body_snippet") or "(no summary)"
            lines += [
                f"### {i}. [{ev.get('source_type','?').upper()}] {ev.get('title','Untitled')}",
                f"**Date:** {date} | **Tags:** {tags}",
                "",
                body,
                "",
            ]
    else:
        lines += [
            "## Evidence Summary",
            "No new evidence in the specified window — brief covers full case context.",
            "",
        ]

    lines += [
        "---",
        "",
        "## 🎙 Audio Overview Prompt",
        "",
        "*Paste this into NotebookLM → Audio Overview → Customize:*",
        "",
        "---",
        "",
        template["audio_overview_prompt"],
        "",
        "---",
        "",
        f"*gem-notebooklm | {now} | RC-2026 | template: {template['id']}*",
        f"*Audio downloads: store OUTSIDE lawmodel1 workspace*",
    ]

    return "\n".join(lines)


# ──────────────── MAIN ────────────────
def run(args):
    # Print the evidentiary firewall notice every time
    print()
    print("━" * 70)
    print(NOT_EVIDENCE_BANNER)
    print("━" * 70)
    print()

    # Load templates
    if not TEMPLATES_FILE.exists():
        log(f"Templates file not found: {TEMPLATES_FILE}", "ERR")
        sys.exit(1)
    with open(TEMPLATES_FILE) as f:
        templates = json.load(f)

    preamble = templates.get("case_context_preamble", "")

    # Select templates
    if args.template:
        selected = [t for t in templates["templates"] if t["id"] == args.template]
        if not selected:
            ids = [t["id"] for t in templates["templates"]]
            log(f"Template '{args.template}' not found. Options: {ids}", "ERR")
            sys.exit(1)
    else:
        selected = sorted(templates["templates"], key=lambda t: t["priority"])

    log(f"Templates: {[t['name'] for t in selected]}")

    # Get evidence (read-only)
    evidence = get_new_evidence(days=args.days)

    # Resolve output directory — prefer --output-dir, fall back to default outside workspace
    output_dir = Path(args.output_dir).expanduser().resolve() if args.output_dir else DEFAULT_BRIEFS_DIR
    output_dir.mkdir(parents=True, exist_ok=True)
    log(f"Output dir: {output_dir}")
    session_id = datetime.now().strftime("%Y-%m-%d_%H-%M")
    brief_paths = []

    for template in selected:
        log(f"Generating brief: {template['name']}")
        content = generate_brief(evidence, template, preamble)
        brief_name = f"{session_id}_{template['id']}.md"
        brief_path = output_dir / brief_name
        brief_path.write_text(content)
        brief_paths.append((template, brief_path))
        log(f"Brief saved: {brief_path}", "OK")

    if args.dry_run:
        log("Dry run complete — briefs generated, no further action.", "OK")
        return

    # Print upload instructions
    print()
    print("═" * 70)
    print("  gem-notebooklm — UPLOAD READY")
    print("═" * 70)
    print()
    print(f"  Session  : {session_id}")
    print(f"  Evidence : {len(evidence)} items (last {args.days} days)")
    print(f"  Briefs   : {len(brief_paths)}")
    print()
    print("  STEPS:")
    print()
    print("  1. Open https://notebooklm.google.com/")
    print(f"  2. Create notebook: 'RC-2026 Deepdive — {session_id}'")
    print()
    print("  3. Upload these briefs as sources:")
    for template, bp in brief_paths:
        print(f"     [{template['id']}]  {bp}")
    print()
    print("  4. For each brief → Audio Overview → Customize")
    print("     Paste the prompt from the '🎙 Audio Overview Prompt' section")
    print("     Select: Long, detailed discussion → Generate")
    print()
    print("  5. Download the MP3 to a folder OUTSIDE this workspace")
    print("     e.g. ~/Desktop/RC-Audio-Overviews/ or an external drive")
    print()
    print("  ✗ Do NOT store audio files inside lawmodel1/")
    print("  ✗ Do NOT upload audio transcripts back to evidence_hub.db")
    print()
    print("═" * 70)
    print()
    log("Done. Briefs are outbound-only.", "OK")


# ──────────────── CLI ────────────────
def main():
    parser = argparse.ArgumentParser(
        description="gem-notebooklm — one-way evidence brief generator for NotebookLM"
    )
    parser.add_argument("--template", default=None,
        help="Template ID (default: all). Use --list-templates to see options.")
    parser.add_argument("--days", type=int, default=30,
        help="Days of recent evidence to include (default: 30)")
    parser.add_argument("--output-dir", default=None,
        help=f"Directory to write briefs to (default: {DEFAULT_BRIEFS_DIR}). "
             "Set this to a path OUTSIDE lawmodel1 to keep the workspace clean.")
    parser.add_argument("--dry-run", action="store_true",
        help="Generate briefs only, skip upload instructions")
    parser.add_argument("--list-templates", action="store_true",
        help="List available templates and exit")

    args = parser.parse_args()

    if args.list_templates:
        with open(TEMPLATES_FILE) as f:
            templates = json.load(f)
        print("\nAvailable Templates:")
        for t in templates["templates"]:
            print(f"  {t['id']:35s} — {t['name']}")
        print()
        return

    run(args)


if __name__ == "__main__":
    main()
